import type { Metadata } from "next";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import { RecoilProvider, ReactQueryProvider } from "common-providers";
import "./globals.css";

export const metadata: Metadata = {
	title: "Vogue Attire",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${GeistSans.variable} ${GeistMono.variable}`}>
				<ReactQueryProvider>
					<RecoilProvider>{children}</RecoilProvider>
				</ReactQueryProvider>
			</body>
		</html>
	);
}
