import type { Metadata } from "next";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import { RecoilProvider, ReactQueryProvider } from "common-providers";
import "./globals.css";
import { GoogleAuthProvider, ThemeProvider } from "@/components/providers";
import { ThemeToggleBtn } from "@/components/common";

export const metadata: Metadata = {
	title: "Vogue Attire",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${GeistSans.variable} ${GeistMono.variable}`}>
				<ReactQueryProvider>
					<RecoilProvider>
						<ThemeProvider>
							<GoogleAuthProvider>
								{children}
								<ThemeToggleBtn />
							</GoogleAuthProvider>
						</ThemeProvider>
					</RecoilProvider>
				</ReactQueryProvider>
			</body>
		</html>
	);
}
